version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet/sdk:6.0 
    steps:
      - checkout
      - run:
          working_directory: OEF-Social_Service
          name: build solution
          command: |
            dotnet build

  test:
    docker:
      - image: dotnet/sdk:6.0 
    steps:
      - checkout
      - run:
          working_directory: OEF-Social_UnitTest
          name: Run unittests
          command: |
            dotnet test
      - run:
          working_directory: OEF-Social_IntegrationTest
          name: Run integrationtests
          command: |
            dotnet test

workflows:
  sample: 
    jobs:
      - build
      - test
