version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: OEF-Social_Service/OEF-Social_Service
          name: build solution
          command: dotnet build

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: OEF-Social_Service/OEF-Social_Service.Services.XUnit
          name: Run unittests
          command: dotnet test
      - run:
          working_directory: OEF-Social_Service/OEF-Social_Service.XIntegration
          name: Run integrationtests
          command: dotnet test
  sonarqube:
    docker:
      - image: 'node:latest'
    steps:
        - checkout
        - sonarcloud/scan:
             project_root: OEF-Social_Service

workflows:
  build: 
    jobs:
      - build
  test: 
    jobs:
      - test
  quality: 
    jobs:
      - sonarqube
